import type { Cafe } from "@/types/cafe";

export const mockCafes: Cafe[] = [
  {
    name: "스타벅스 강동구청DT점",
    brand: "Starbucks",
    address: "서울특별시 강동구 성내로 32",
    depositCupSupported: true,
    personalCupDiscountSupported: true,
  },
  {
    name: "스타벅스 강동역점",
    brand: "Starbucks",
    address: "서울특별시 강동구 천호대로 1089",
    depositCupSupported: true,
    personalCupDiscountSupported: true,
  },
  {
    name: "스타벅스 강동암사DT점",
    brand: "Starbucks",
    address: "서울특별시 강동구 올림픽로 796",
    depositCupSupported: true,
    personalCupDiscountSupported: true,
  },
  {
    name: "스타벅스 둔촌동점",
    brand: "Starbucks",
    address: "서울특별시 강동구 양재대로 1365",
    depositCupSupported: true,
    personalCupDiscountSupported: true,
  },
  {
    name: "스타벅스 길동점",
    brand: "Starbucks",
    address: "서울특별시 강동구 양재대로 1487",
    depositCupSupported: true,
    personalCupDiscountSupported: true,
  },
  {
    name: "스타벅스 명일역점",
    brand: "Starbucks",
    address: "서울특별시 강동구 고덕로 399",
    depositCupSupported: true,
    personalCupDiscountSupported: true,
  },
  {
    name: "스타벅스 고덕그라시움점",
    brand: "Starbucks",
    address: "서울특별시 강동구 고덕비즈밸리로 26",
    depositCupSupported: true,
    personalCupDiscountSupported: true,
  },
  {
    name: "디저트39 강동역점",
    brand: "Dessert39",
    address: "서울특별시 강동구 천호대로 1092",
    depositCupSupported: true,
    personalCupDiscountSupported: false,
  },
  {
    name: "할리스 천호로데오점",
    brand: "Hollys",
    address: "서울특별시 강동구 올림픽로70길 61",
    depositCupSupported: false,
    personalCupDiscountSupported: true,
  },
  {
    name: "이디야커피 강동성내점",
    brand: "EDIYA",
    address: "서울특별시 강동구 풍성로 162",
    depositCupSupported: false,
    personalCupDiscountSupported: true,
  },
  {
    name: "투썸플레이스 둔촌플래그십점",
    brand: "A TWOSOME PLACE",
    address: "서울특별시 강동구 양재대로 1360",
    depositCupSupported: false,
    personalCupDiscountSupported: true,
  },
  {
    name: "마루브",
    brand: "서울시 개인컵 할인 매장",
    address: "서울특별시 강동구 상일로 135",
    depositCupSupported: false,
    personalCupDiscountSupported: true,
    sourceLabel: "서울시 지도",
    sourceUrl: "https://map.seoul.go.kr/smgis/short2.jsp?p=6PLNo",
  },
];
