import type { DailyMission, MissionHistoryEntry } from "@/types/mission";

export const mockDailyMissions: DailyMission[] = [
  {
    id: "mission-tumbler-class",
    title: "텀블러나 개인 컵으로 물 마시기",
    category: "일회용품 줄이기",
    summary: "오늘은 일회용 컵 대신 개인 컵이나 텀블러를 사용해 보세요.",
    ecoMoney: 60,
    actionDifficulty: "low",
    proofDifficulty: "low",
    space: "indoor",
    durationMinutes: 5,
    location: "교실 또는 집",
    supplyLevel: "minimal",
    supplyNote: "개인 컵이나 텀블러 1개",
    weatherSensitivity: "low",
    weekAvailability: "any",
    proofMethod: "photo",
    proofGuide: "개인 컵이나 텀블러를 사용하는 사진 1장",
    safetyNote: "유리컵보다 가벼운 물병이나 텀블러를 권장해요.",
    directImpact: "일회용 컵 사용을 줄여 쓰레기 발생을 줄일 수 있어요.",
    exclusions: ["새 컵 구매 필수 아님", "카페 방문 필수 아님"],
    tags: ["텀블러", "일회용품", "물마시기"],
  },
  {
    id: "mission-bin-sort",
    title: "오늘 나온 재활용 쓰레기 바르게 분리배출하기",
    category: "분리배출",
    summary: "플라스틱, 종이, 캔을 한 번 더 확인하고 올바르게 분리해 보세요.",
    ecoMoney: 70,
    actionDifficulty: "low",
    proofDifficulty: "low",
    space: "indoor",
    durationMinutes: 10,
    location: "집 또는 학교",
    supplyLevel: "none",
    supplyNote: "준비물 없음",
    weatherSensitivity: "low",
    weekAvailability: "any",
    proofMethod: "photo",
    proofGuide: "분리된 쓰레기통 또는 분리 전후 사진 1장",
    safetyNote: "날카로운 물건은 맨손으로 만지지 않아요.",
    directImpact: "재활용 효율을 높이고 일반 쓰레기를 줄일 수 있어요.",
    exclusions: ["유리 파손물 맨손 처리", "위험 폐기물 처리"],
    tags: ["재활용", "플라스틱", "종이"],
  },
  {
    id: "mission-light-off",
    title: "비는 시간 10분 동안 불필요한 전등 끄기",
    category: "에너지 절약",
    summary: "교실이나 집에서 비어 있는 공간의 전등이 켜져 있는지 확인하고 꺼 보세요.",
    ecoMoney: 50,
    actionDifficulty: "low",
    proofDifficulty: "low",
    space: "indoor",
    durationMinutes: 5,
    location: "교실 또는 집",
    supplyLevel: "none",
    supplyNote: "준비물 없음",
    weatherSensitivity: "low",
    weekAvailability: "any",
    proofMethod: "photo",
    proofGuide: "전등을 끄기 전후가 보이는 사진 1장",
    safetyNote: "안전상 필요한 조명은 끄지 않아요.",
    directImpact: "불필요한 전기 사용을 바로 줄일 수 있어요.",
    exclusions: ["공용 설비 차단", "안전 조명 끄기"],
    tags: ["전등", "전기", "절약"],
  },
  {
    id: "mission-stairs-one-floor",
    title: "한 층 정도는 엘리베이터 대신 계단 이용하기",
    category: "친환경 이동",
    summary: "학교나 건물 안에서 짧은 이동은 계단으로 바꿔 보세요.",
    ecoMoney: 75,
    actionDifficulty: "medium",
    proofDifficulty: "medium",
    space: "outdoor",
    durationMinutes: 10,
    location: "학교 또는 공용 공간",
    supplyLevel: "none",
    supplyNote: "준비물 없음",
    weatherSensitivity: "low",
    weekAvailability: "weekday",
    proofMethod: "photo",
    proofGuide: "계단 앞이나 이동 후 사진 1장과 현재 위치 인증",
    safetyNote: "뛰지 말고 손잡이를 잡고 이동해요.",
    directImpact: "짧은 이동에서 에너지 사용을 줄일 수 있어요.",
    exclusions: ["몸이 불편한 날", "무거운 짐을 든 상태"],
    tags: ["계단", "이동", "학교"],
  },
  {
    id: "mission-pickup-five",
    title: "통학로나 학교 주변에서 쓰레기 5개 줍기",
    category: "줍깅",
    summary: "안전한 구역에서 작은 쓰레기 5개를 주워 올바른 곳에 버려 보세요.",
    ecoMoney: 80,
    actionDifficulty: "high",
    proofDifficulty: "medium",
    space: "outdoor",
    durationMinutes: 10,
    location: "학교 앞 또는 통학로",
    supplyLevel: "minimal",
    supplyNote: "장갑이 있으면 좋아요.",
    weatherSensitivity: "high",
    weekAvailability: "any",
    proofMethod: "photo",
    proofGuide: "주운 쓰레기를 버리기 전에 모아 찍은 사진 1장과 현재 위치 인증",
    safetyNote: "차도 근처, 깨진 유리, 날카로운 쓰레기는 줍지 않아요.",
    directImpact: "주변 환경을 바로 깨끗하게 만들 수 있어요.",
    exclusions: ["비 오는 날", "차도 근처", "깨진 유리 줍기"],
    tags: ["줍깅", "통학로", "야외"],
  },
];

export const mockRecentMissionHistory: MissionHistoryEntry[] = [
  {
    date: "2026-06-11",
    missionId: "mission-bin-sort",
    category: "분리배출",
    actionDifficulty: "low",
    space: "indoor",
    tags: ["재활용", "플라스틱", "종이"],
  },
  {
    date: "2026-06-12",
    missionId: "mission-light-off",
    category: "에너지 절약",
    actionDifficulty: "low",
    space: "indoor",
    tags: ["전등", "전기", "절약"],
  },
];
