import type { DailyMission, MissionHistoryEntry } from "@/types/mission";

export const mockDailyMissions: DailyMission[] = [
  {
    id: "mission-tumbler",
    title: "텀블러나 개인 컵으로 음료 마시기",
    category: "일회용품 줄이기",
    summary: "오늘 하루는 일회용 컵 대신 개인 컵이나 텀블러를 사용해 보세요.",
    ecoMoney: 80,
    actionDifficulty: "low",
    proofDifficulty: "low",
    space: "indoor",
    durationMinutes: 10,
    location: "학교 또는 카페",
    supplyLevel: "minimal",
    supplyNote: "텀블러 또는 개인 컵 1개",
    weatherSensitivity: "low",
    weekAvailability: "any",
    proofMethod: "photo",
    proofGuide: "개인 컵을 사용한 모습을 사진으로 남겨 보세요.",
    safetyNote: "뜨거운 음료를 들고 이동할 때는 조심해 주세요.",
    directImpact: "일회용 컵 쓰레기를 줄일 수 있어요.",
    exclusions: ["새 텀블러 구매 필수 아님"],
    tags: ["텀블러", "카페", "일회용품"],
  },
  {
    id: "mission-sort-trash",
    title: "재활용품 바르게 분리배출하기",
    category: "분리배출",
    summary: "플라스틱, 캔, 종이를 한 번 더 확인하고 올바르게 분리배출해 보세요.",
    ecoMoney: 90,
    actionDifficulty: "low",
    proofDifficulty: "low",
    space: "indoor",
    durationMinutes: 10,
    location: "집 또는 학교",
    supplyLevel: "none",
    supplyNote: "별도 준비물 없음",
    weatherSensitivity: "low",
    weekAvailability: "any",
    proofMethod: "photo",
    proofGuide: "분리배출한 결과를 사진으로 기록해 보세요.",
    safetyNote: "날카로운 캔 뚜껑에 손이 베이지 않게 조심해 주세요.",
    directImpact: "재활용률을 높이고 혼합 폐기물을 줄일 수 있어요.",
    exclusions: ["위험 폐기물 처리"],
    tags: ["분리배출", "재활용", "플라스틱"],
  },
  {
    id: "mission-light-off",
    title: "사용하지 않는 조명 끄기",
    category: "에너지 절약",
    summary: "교실이나 집에서 비어 있는 공간의 조명을 꺼서 전기를 아껴 보세요.",
    ecoMoney: 70,
    actionDifficulty: "low",
    proofDifficulty: "low",
    space: "indoor",
    durationMinutes: 5,
    location: "집 또는 학교",
    supplyLevel: "none",
    supplyNote: "준비물 없음",
    weatherSensitivity: "low",
    weekAvailability: "any",
    proofMethod: "checklist",
    proofGuide: "오늘 껐던 조명을 체크리스트로 남겨 보세요.",
    safetyNote: "안전상 필요한 조명은 끄지 마세요.",
    directImpact: "불필요한 전력 사용을 줄일 수 있어요.",
    exclusions: ["공용 설비 차단"],
    tags: ["전기", "조명", "절약"],
  },
];

export const mockRecentMissionHistory: MissionHistoryEntry[] = [
  {
    date: "2026-06-11",
    missionId: "mission-sort-trash",
    category: "분리배출",
    actionDifficulty: "low",
    space: "indoor",
    tags: ["분리배출", "재활용", "플라스틱"],
  },
  {
    date: "2026-06-12",
    missionId: "mission-light-off",
    category: "에너지 절약",
    actionDifficulty: "low",
    space: "indoor",
    tags: ["전기", "조명", "절약"],
  },
];
